name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Build
        run: dotnet build .\NyaLauncher.Clock.slnx -c Release
      - name: Test
        run: dotnet run --project .\tests\NyaLauncher.Clock.Tests.csproj -c Release
      - name: Package
        shell: pwsh
        run: .\package.ps1
